#219 Collapsing of subQuery properties
anvilco/spectaql pull request #300
Opened 2022-04-14 08:45 UTC by amaleszewski

Hello, I've created a PR for collapsing a subQuery properties as I've mentioned in #219 issue.

2022-04-14 21:18 UTC, newhouse requested changes
@amaleszewski thank you so much for this PR!

I love that you've submitted this rather than just keep it to yourself as part of a fork, and I love this option.

I do just have a few requests around where the option belongs, but other than that I'm willing to accept it after those changes.

I'd love to see a test for this if possible, but there's no pattern or existing module for this area of the code so far, so that's probably a bit much to ask of you...and I'll have to add it myself at some point.

Thanks again!

2022-04-14 21:18 UTC, newhouse commented on config-example.yml
> +  collapseSubQueryDepth: 3
I think this should be named something else like `typeExpansionDepth`.

And I think it should be placed under `introspection` options, and not the `extensions` area.

2022-04-14 21:18 UTC, newhouse commented on src/index.js
> +  collapseSubQueryDepth: 1
This will need to be moved to the `introspectionOptionDefaults`, please.

2022-04-15 07:29 UTC, amaleszewski commented
Thanks for response, I will try to fix that in the next week according to the remarks you added, because I don't have time in this week.

I'm also not sure about adding new tests, because it could be time-consuming for me but I will try :)

2022-04-15 15:07 UTC, newhouse commented
> Thanks for response, I will try to fix that in the next week according to the remarks you added, because I don't have time in this week.
> 
> I'm also not sure about adding new tests, because it could be time-consuming for me but I will try :)

In the interest of time, I have taken your work and just brought it across the finish line myself in another PR:
https://github.com/anvilco/spectaql/pull/302

I'll close this PR now as this change has been merged and is out in `1.1.0`.

Thanks for your contribution, @amaleszewski !!!

2022-04-15 15:07 UTC, closed without merging